// Lint this view
const levels = [
  {
    name: "hello",
    message: "GREETINGS PROFESSOR FALKEN",
    winnerAlert: "",
    src: "/images/black.jpg",
    font: "Orbitron",
    color: "#56CCDB",
    size: "36px",
    winnerGif: "/gifs/hello.gif",
    animationStyle: "/stylus/type.styl",
    soundtrack: "/soundtrack/WarGames.mp3",
    soundtrackName: "WarGames"
  },
  {
    name: "tic tac toe",
    message: "SHALL WE PLAY A GAME?",
    winnerAlert: "",
    src: "/images/black.jpg",
    font: "Orbitron",
    color: "#56CCDB",
    size: "36px",
    winnerGif: "/gifs/tictactoe.gif",
    animationStyle: "/stylus/type.styl",
    soundtrack: "/soundtrack/WarGames.mp3",
    soundtrackName: "WarGames"
  },
  {
    name : "programs",
    src : "/images/tron.jpg",
    message : "Greetings ....",
    winnerAlert : "",
    font: "Russo One",
    color: "#4CD0F5",
    size: "36px",
    winnerGif: "/gifs/user.gif",
    animationStyle: "/stylus/type.styl",
    soundtrack : "/soundtrack/Tron.mp3",
    soundtrackName : "Tron"
  },
  {
    name : "eat",
    src : "/images/jurassicpark1.jpg",
    message : ` John Hammond: All major theme parks have delays.
                When they opened Disneyland in 1956, nothing worked! <br>
                Ian Malcolm: Yeah, but, John,
                if The Pirates of the Caribbean breaks down,
                the pirates don't ......the tourists.`,
    winnerAlert : "Remind me to thank John for the wonderful weekend.",
    font: "Oswald",
    color: "#b306f0",
    size: "36px",
    winnerGif: "/gifs/eat.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/JurassicPark.mp3",
    soundtrackName : "JurassicPark"
  },
  {
    name : "butterfingers",
    src : "/images/jurassicpark3.jpg",
    message : "Dennis, our lives are in your hands and you've got ......",
    winnerAlert : "Uh uh uh! You didn't say the magic word! Uh uh uh! Uh uh uh!",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/butterfingers.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/JurassicPark.mp3",
    soundtrackName : "JurassicPark"
  },
  {
    name : "shit",
    src : "/images/jurassicpark2.jpg",
    message : "That is one big pile of ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/shit.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/JurassicPark.mp3",
    soundtrackName : "JurassicPark"
  },
  {
    name : "expelled",
    src : "/images/harrypotter1.jpg",
    message : "We could all have been killed - or worse ......",
    winnerAlert : "",
    font: "Rock Salt",
    color: "#F76605",
    size: "42px",
    winnerGif: "/gifs/expelled.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/HarryPotter.mp3",
    soundtrackName : "HarryPotter"
  },
  {
    name : "teaspoon",
    src : "/images/harrypotter2.jpg",
    message : "Just because you have the emotional range of a ......",
    winnerAlert : "",
    font: "Rock Salt",
    color: "#F76605",
    size: "42px",
    winnerGif: "/gifs/teaspoon.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/HarryPotter.mp3",
    soundtrackName : "HarryPotter"
  },
  {
    name : "good",
    src : "/images/harrypotter3.jpg",
    message : "I solemnly swear I am up to no ......",
    winnerAlert : "",
    font: "Rock Salt",
    color: "#F76605",
    size: "42px",
    winnerGif: "/gifs/good.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/HarryPotter.mp3",
    soundtrackName : "HarryPotter"
  },
  {
    name : "die",
    src : "/images/goonies.jpg",
    message : "Goonies never say ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#b306f0",
    size: "42px",
    winnerGif: "/gifs/die.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Goonies.mp3",
    soundtrackName : "Goonies"
  },
  {
    name : "rule",
    src : "/images/lotr.jpg",
    message : "One Ring to ......them all",
    winnerAlert : "",
    font: "Eagle lake",
    color: "#c3ce15",
    size: "36px",
    winnerGif: "/gifs/rule.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/LOTR.mp3",
    soundtrackName : "LOTR"
  },
  {
    name : "bind",
    src : "/images/lotr2.jpg",
    message : ` One Ring to find them,
                One Ring to bring them all, <br>
                and in the darkness ......them`,
    winnerAlert : "",
    font: "Eagle Lake",
    color: "#c3ce15",
    size: "36px",
    winnerGif: "/gifs/bind.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/LOTR.mp3",
    soundtrackName : "LOTR"
  },
  {
    name : "carpet",
    src : "/images/starwars1.jpg",
    message : "Would somebody get this big walking ...... out of my way?!",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/carpet.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/StarWars.mp3",
    soundtrackName : "StarWars"
  },
  {
    name : "disturbing",
    src : "/images/starwars2.jpg",
    message : "I find your lack of faith ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/disturbing.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/StarWars.mp3",
    soundtrackName : "StarWars"
  },
  {
    name : "droids",
    src : "/images/starwars3.jpg",
    message : "These arent' the ......  you're looking for.",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/droids.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/StarWars.mp3",
    soundtrackName : "StarWars"
  },
  {
    name : "short",
    src : "/images/starwars4.jpg",
    message : "Aren't you a little ...... for a Stormtrooper?",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/short.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/StarWars.mp3",
    soundtrackName : "StarWars"
  },
  {
    name : "uncle nicnak",
    src : "/images/adamsfamily1.jpg",
    message : ` Uncle Nicnak's winter wardobe. <br>
                Uncle Nicnak's summer wardrobe ......`,
    winnerAlert : "",
    font: "Pacifico",
    color: "#C20527",
    size: "46px",
    winnerGif: "/gifs/unclenicnak.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/AdamsFamily.mp3",
    soundtrackName : "AdamsFamily"
  },
  {
    name : "homicidal maniac",
    src : "/images/adamsfamily2.jpg",
    message : "I'm a ...... they look just like everyone else.",
    winnerAlert : "",
    font: "Pacifico",
    color: "#C20527",
    size: "52px",
    winnerGif: "/gifs/maniac.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/AdamsFamily.mp3",
    soundtrackName : "AdamsFamily"
  },
  {
    name : "antenna",
    src : "/images/adamsfamily3.jpg",
    message : "Children, we're starting. Put down that ......",
    winnerAlert : "",
    font: "Pacifico",
    color: "#C20527",
    size: "52px",
    winnerGif: "/gifs/antenna.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/AdamsFamily.mp3",
    soundtrackName : "AdamsFamily"
  },
  {
    name : "die",
    src : "/images/residentevil.jpg",
    message : "You're all going to ......down here",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA0505",
    size: "42px",
    winnerGif: "/gifs/die2.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/ResidentEvil.mp3",
    soundtrackName : "ResidentEvil"
  },
  {
    name : "betrayel",
    src : "/images/firefly1.gif",
    message : "Curse your sudden but inevitable ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#435BF7",
    size: "42px",
    winnerGif: "/gifs/betrayal.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Firefly.mp3",
    soundtrackName : "Firefly"
  },
  {
    name : "brain",
    src : "/images/firefly2.jpg",
    message : "Also, I can kill you with my ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#435BF7",
    size: "42px",
    winnerGif: "gifs/brain.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Firefly.mp3",
    soundtrackName : "Firefly"
  },
  {
    name : "spaceship",
    src : "/images/firefly4.jpg",
    message : ` Wash: Psychic, though?
                That sounds like something out of science fiction. <br>
                Zoe: We live in a ...... dear.`,
    winnerAlert : "",
    font: "Oswald",
    color: "#435BF7",
    size: "42px",
    winnerGif: "/gifs/spaceship.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Firefly.mp3",
    soundtrackName : "Firefly"
  },
  {
    name : "strange",
    src : "/images/ghostbusters.jpg",
    message : "If there's something ...... in your neighborhood, who ya gonna call?",
    winnerAlert : "I ain't afraid of no ghosts",
    font: "Oswald",
    color: "#1975F7",
    size: "42px",
    winnerGif: "/gifs/strange.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Ghostbusters.mp3",
    soundtrackName : "Ghostbusters"
  },
  {
    name : "ghostbusters",
    src : "/images/ghostbusters.jpg",
    message : "If there's something weird and it don't look good, who ya gonna call......",
    winnerAlert : "",
    font: "Oswald",
    color: "#1975F7",
    size: "42px",
    winnerGif: "/gifs/ghostbusters.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Ghostbusters.mp3",
    soundtrackName : "Ghostbusters"
  },
  {
    name : "cartoon",
    src : "/images/pagemaster1.jpg",
    message : "I'm a ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#F536C2",
    size: "42px",
    winnerGif: "/gifs/cartoon.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Pagemaster.mp3",
    soundtrackName : "Pagemaster"
  },
  {
    name : "tooth fairy",
    src : "/images/pagemaster2.jpg",
    message : ` Fantasy! <br>
                Naturally. Who were you expecting, Honey? The ......`,
    winnerAlert : "",
    font: "Oswald",
    color: "#F536C2",
    size: "42px",
    winnerGif: "/gifs/toothfairy.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Pagemaster.mp3",
    soundtrackName : "Pagemaster"
  },
  {
    name : "frontier",
    src : "/images/startrek.jpg",
    message : "Space, the final ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#9499A1",
    size: "42px",
    winnerGif: "/gifs/frontier.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/StarTrek.mp3",
    soundtrackName : "StarTrek"
  },
  {
    name : "switch",
    src : "/images/LostInSpace.jpg",
    message : "And the monkey flips the ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#9499A1",
    size: "42px",
    winnerGif: "/gifs/switch.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/LostInSpace.mp3",
    soundtrackName : "LostInSpace"
  },
  {
    name : "bitch",
    src : "/images/aliens.jpg",
    message : "Get away from her, you ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA9C05",
    size: "42px",
    winnerGif: "/gifs/bitch.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/Aliens.mp3",
    soundtrackName : "Aliens"
  },
  {
    name : "bad english",
    src : "/images/FifthElement1.jpg",
    message : "Listen lady, I only speak two languages: <br> English and ......",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA6B05",
    size: "42px",
    winnerGif: "/gifs/badenglish.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/FifthElement.mp3",
    soundtrackName : "FifthElement"
  },
  {
    name : "fire",
    src : "/images/FifthElement2.jpg",
    message : "Korben, my man! I ain't got no ......!",
    winnerAlert : "",
    font: "Oswald",
    color: "#FA6B05",
    size: "42px",
    winnerGif: "/gifs/fire.gif",
    animationStyle: "",
    soundtrack : "/soundtrack/FifthElement.mp3",
    soundtrackName : "FifthElement"
  }
];

export default levels;

